title: Filemakr Blog
description: Blog powered by Jekyll and GitHub Pages
baseurl: "/blog"
url: "https://filemakr.github.io"

theme: minima
permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-feed
