title: Filemakr Blog
description: Final Year Projects & Guides
baseurl: "/blog"     # 👈 required for GitHub Pages project sites
url: "https://filemakr.github.io"

theme: minima        # or any Jekyll theme
plugins:
  - jekyll-feed
